%  Auto-generated by MATLAB on 25-Nov-2014 11:56:31
%  Modified by Ugo Louche

%Get rid of anything that might pose a problem
clear all

%load data
load AppFrequency;
ymatrix1 = AppFrequency(:,1:12)';

%reorder Bars
tmp = ymatrix1(:,1);
ymatrix1(:,1) = ymatrix1(:,2);
ymatrix1(:,2) = ymatrix1(:,3);
ymatrix1(:,3) = tmp;

% Create figure
figure1 = figure('XVisual','');

% Create axes
axes1 = axes('Parent',figure1,'YTick',[0.3 0.6 0.9],'XTick',[0 6 12],...
    'FontSize',25);
xlim(axes1,[0 13]);
box(axes1,'on');
hold(axes1,'all');


% Create multiple lines using matrix input to bar
bar1 = bar(ymatrix1,'BarWidth',2 ,'Parent',axes1);
set(bar1(1),'DisplayName','Smallest Error', 'FaceColor', [0.75 0 0]);
set(bar1(2),'DisplayName','Random Error', 'FaceColor', [0 0.75 0]);
set(bar1(3),'DisplayName','Largest Error', 'FaceColor', [0 0 0.75]);

%c={'plot 1' 'plot 2' 'plot 3'}; % legend list
order=[3 2 1];
legend(bar1(order));


% Create xlabel
xlabel('Cutting Plane');

% Create ylabel
ylabel('Query Frequency');

% Create legend
legend(axes1,'show');

