%  Auto-generated by MATLAB on 28-Nov-2014 15:53:21

%Get rid of anything that might pose a problem 
clear all

%load data
load pool500;
load pool1000;
xvector_tmp = [1:201]';
ymatrix1_tmp = [pool500.distSVM pool1000.distSVM pool500.distBPM pool1000.distBPM];

%only keep 1 data out of jmax
j = 1;
for i=1:size( xvector_tmp, 1 )
    if (j == 20) %<-- jmax
        j = 1;
    end
    
    if (j == 1)
        if ( i == 1)
            ymatrix1 = ymatrix1_tmp(1, :);
            xvector = xvector_tmp(1, 1);
        else
            ymatrix1 = [ymatrix1; ymatrix1_tmp(i, :)];
            xvector = [xvector; xvector_tmp(i, :)];
        end
    end 
    
    j = j + 1;
end

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YTick',[0 2 4],'XTick',[50 100 150 200],...
    'FontSize',21);
xlim(axes1, [1 201]);
ylim(axes1, [0 5.5])
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input
plot1 = plot(xvector, ymatrix1, 'Parent',axes1);
set(plot1(1),'DisplayName', 'A-SVM, 500 Pts', 'Color', [0 0 0.75], 'MarkerSize', 13,'Marker', 'o', 'LineWidth', 4, 'LineStyle', '--');
set(plot1(2),'DisplayName', 'A-SVM, 1000 Pts', 'Color', [0 0.75 0], 'MarkerSize', 13,'Marker', 'o', 'LineWidth', 4, 'LineStyle', ':');
set(plot1(3),'DisplayName', 'A-BPM, 500 Pts', 'Color', [0.75 0 0], 'MarkerSize', 13,'Marker', 's', 'LineWidth', 4, 'LineStyle', '--');
set(plot1(4),'DisplayName', 'A-BPM, 1000 Pts', 'Color', [0.0 0.75 0.75], 'MarkerSize', 13,'Marker', 's', 'LineWidth', 4, 'LineStyle', ':');

% Create xlabel
xlabel('Number of queries');

% Create ylabel
ylabel('Accuracy');

% Create legend
legend(axes1,'show', 'Location', 'NorthWest');

