%  Auto-generated by MATLAB on 28-Nov-2014 15:53:21

%Get rid of anything that might pose a problem 
clear all

%load data
load Reuters500Res;
%loak;d ThyroidRes
pool500 = result;
load Reuters1000Res;
%load DiabetisRes
pool1000 = result;
xvector_tmp = [1:101]';
ymatrix1_tmp = [pool500.mAccSVM pool1000.mAccSVM pool500.mAccBPM pool1000.mAccBPM];
error1_tmp = [pool500.stdAccSVM pool1000.stdAccSVM pool500.stdAccBPM pool1000.stdAccBPM];

%only keep 1 data out of jmax
j = 1;
for i=1:size( xvector_tmp, 1 )
    if (j == 5) %<-- jmax
        j = 1;
    end
    
    if (j == 1)
        if ( i == 1)
            ymatrix1 = ymatrix1_tmp(1, :);
            xvector = xvector_tmp(1, 1);
            error1 = error1_tmp(1, :);
        else
            ymatrix1 = [ymatrix1; ymatrix1_tmp(i, :)];
            xvector = [xvector; xvector_tmp(i, :)];
            error1 = [error1; error1_tmp(i, :)];
        end
    end 
    
    j = j + 1;
end
xvector = repmat(xvector, 1, 4);

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YTick',[0.4 0.6 0.8 1],'XTick',[0 25 50 75 100],...
    'FontSize',21);
xlim(axes1, [1 40]);
ylim(axes1, [0.6 1])
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input
plot1 = plot(xvector, ymatrix1, 'Parent',axes1);
set(plot1(1),'DisplayName', 'Active SVM, 500 Points', 'Color', [0 0 0.75], 'MarkerSize', 13,'Marker', 'o', 'LineWidth', 4, 'LineStyle', '--');
set(plot1(2),'DisplayName', 'Active SVM, 1000 Points', 'Color', [0 0.75 0], 'MarkerSize', 13,'Marker', 'o', 'LineWidth', 4, 'LineStyle', ':');
set(plot1(3),'DisplayName', 'Active BPM, 500 Points', 'Color', [0.75 0 0], 'MarkerSize', 13,'Marker', 's', 'LineWidth', 4, 'LineStyle', '--');
set(plot1(4),'DisplayName', 'Active BPM, 1000 Points', 'Color', [0.0 0.75 0.75], 'MarkerSize', 13,'Marker', 's', 'LineWidth', 4, 'LineStyle', ':');

% Create xlabel
xlabel('Number of queries');

% Create ylabel
ylabel('Accuracy');

% Create legend
legend(axes1,'show', 'Location', 'SouthEast');

