%  Auto-generated by MATLAB on 28-Nov-2014 15:53:21

%Get rid of anything that might pose a problem 
clear all

%load data
load NbCP;
ymatrix1_tmp = [NbCP.Biggest; NbCP.Smallest; NbCP.Random]';
xvector_tmp = [0.01:0.01:0.30]';

%only keep 1 data out of 10
j = 1;
for i=1:size( xvector_tmp, 1 )
    if (j == 4)
        j = 1;
    end
    
    if (j == 1)
        if ( i == 1)
            ymatrix1 = ymatrix1_tmp(1, :);
            xvector = xvector_tmp(1, 1);
        else
            ymatrix1 = [ymatrix1; ymatrix1_tmp(i, :)];
            xvector = [xvector; xvector_tmp(i, :)];
        end
    end 
    
    j = j + 1;
end

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YTick',[0 5 10 15 20],'XTick',[0 0.1 0.2 0.3],...
    'FontSize',25);
xlim(axes1,[0 0.3]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input
plot1 = plot(xvector, ymatrix1, 'Parent',axes1);
set(plot1(1),'DisplayName', 'Largest Error', 'Color', [0 0 0.75], 'MarkerSize', 12,'Marker', 's', 'LineWidth', 5, 'LineStyle', '-');
set(plot1(2),'DisplayName', 'Smallest Error', 'Color', [0 0.75 0], 'MarkerSize', 12,'Marker', 'o', 'LineWidth', 5, 'LineStyle', '--');
set(plot1(3),'DisplayName', 'Random Error', 'Color', [0.75 0 0], 'MarkerSize', 12,'Marker', 'v', 'LineWidth', 5, 'LineStyle', '-.');

% Create xlabel
xlabel('Margins');

% Create ylabel
ylabel('# CP');

% Create legend
legend(axes1,'show');

