%  Auto-generated by MATLAB on 28-Nov-2014 15:53:21

%Get rid of anything that might pose a problem 
clear all

%load data
load UpPerCP;
ymatrix1 = UpPerCP';

%reorder Bars
tmp = ymatrix1(:,2);
ymatrix1(:,2) = ymatrix1(:,3);
ymatrix1(:,3) = tmp;

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YTick',[100 200],'XTick',[0 8 16],...
    'FontSize',25);
xlim(axes1,[0 17]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to bar
bar1 = bar(ymatrix1,'BarWidth',2,'Parent',axes1);
set(bar1(1),'DisplayName','Largest Error', 'FaceColor', [0 0 0.75]);
set(bar1(2),'DisplayName','Random Error', 'FaceColor', [0 0.75 0]);
set(bar1(3),'DisplayName','Smallest Error', 'FaceColor', [0.75 0 0]);

% Create xlabel
xlabel('CP iterations');

% Create ylabel
ylabel('# internal updates');

% Create legend
legend(axes1,'show');

